name: Test

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main
      - develop/*
    paths-ignore:
      - '**.md'

jobs:
  setup-version:
    runs-on: ${{ matrix.operating-system }}
    env:
      config: 'Release'
    strategy:
      fail-fast: true
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macOS-latest]
        dotnet-version: ['5.0']
    steps:
      - name: Checkout
        uses: actions/checkout@2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.202
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration $config --no-restore
      - name: Set build number
        id: PR_NUMBER
        if: ${{ github.event_name == 'pull_request' }}
        uses: kkak10/pr-number-action@v1.3
      - name: Set test title
        run: |
          if ${{ github.event_name == 'pull_request' }}
          then
            echo "::set-env nam=title::Test Run for PR #${{steps.PR_NUMBER.outputs.pr}} (${{github.run_number}})"
            echo "::set-env name=file_name::TestReport.${{steps.PR_NUMBER.outputs.pr}}.${{github.run_number}}.md"
          else
            echo "::set-env name=title::Test Run ${{github.run_number}}"
            echo "::set-env name=file_name::TestReport.${{github.run_number}}.md"
          fi
      - name: Test
        run: dotnet test --no-restore --no-build --configuration $config --logger:"liquid.md;LogFileName=${{github.workspace}}/${{env.file_name}};Title=${{env.title}};"
      - name: Upload Test Report
        uses: actions/upload-artifact@v2
        if: ${{always()}}
        with:
          name: 'Test Run'
          path: ${{github.workspace}}/${{env.file_name}}
      - name: Comment PR
        uses: machine-learning-apps/pr-comment@master
        if: ${{ github.event_name == 'pull_request' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: ${{env.file_name}}
      